// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAb5ffsF8vIqRlGYwv-7Nl-XSn6A7OBQ0',
    appId: '1:916519282950:web:11ca937284b25166935687',
    messagingSenderId: '916519282950',
    projectId: 'daar-4ee4f',
    authDomain: 'daar-4ee4f.firebaseapp.com',
    storageBucket: 'daar-4ee4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBa63ld-U0w6GYuOD5ARyDo4Itb5HFi7E',
    appId: '1:916519282950:android:6f72e5d185da4762935687',
    messagingSenderId: '916519282950',
    projectId: 'daar-4ee4f',
    storageBucket: 'daar-4ee4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoUrP9Fclo46jjUal4-xawBG8BmXoBsS4',
    appId: '1:916519282950:ios:61079e14efc3e09b935687',
    messagingSenderId: '916519282950',
    projectId: 'daar-4ee4f',
    storageBucket: 'daar-4ee4f.appspot.com',
    iosBundleId: 'com.example.daar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoUrP9Fclo46jjUal4-xawBG8BmXoBsS4',
    appId: '1:916519282950:ios:61079e14efc3e09b935687',
    messagingSenderId: '916519282950',
    projectId: 'daar-4ee4f',
    storageBucket: 'daar-4ee4f.appspot.com',
    iosBundleId: 'com.example.daar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAb5ffsF8vIqRlGYwv-7Nl-XSn6A7OBQ0',
    appId: '1:916519282950:web:f37d1a552535825d935687',
    messagingSenderId: '916519282950',
    projectId: 'daar-4ee4f',
    authDomain: 'daar-4ee4f.firebaseapp.com',
    storageBucket: 'daar-4ee4f.appspot.com',
  );
}
